name: Latest blog post workflow
on:
  schedule:
    # Runs every hour (you can change this)
    - cron: '0 */12 * * *'
  workflow_dispatch:
    # Allows manual triggering

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://dev.to/feed/emmanuelarhu"
          max_post_count: 5
          template: "- [$title]($url) - *$date*"
          date_format: "mmm dd, yyyy"
